apiVersion: community.kurrent.io/v1
kind: KurrentCluster
metadata:
  labels:
    app.kubernetes.io/name: kurrentcluster
    app.kubernetes.io/instance: kurrentcluster-advanced
    app.kubernetes.io/part-of: kurrentdb-community-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kurrentdb-community-operator
  name: kurrentcluster-advanced
spec:
  # 5-node cluster for high availability
  size: 5
  image: docker.kurrent.io/kurrent-latest/kurrentdb:latest
  imagePullPolicy: IfNotPresent
  
  # Storage configuration with custom storage class
  storage:
    size: "50Gi"
    storageClassName: "fast-ssd"
    accessModes:
      - ReadWriteOnce
  
  # Network configuration with LoadBalancer
  network:
    serviceType: LoadBalancer
    externalPort: 2113
    internalPort: 2113
    gossipPort: 2113
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  
  # TLS configuration with custom certificates
  tls:
    enabled: true
    autoGenerate: false
    certificatesSecretName: "kurrentdb-custom-certs"
    caSecretName: "kurrentdb-ca-certs"
  
  # Resource requirements for production workload
  resources:
    requests:
      memory: "8Gi"
      cpu: "2"
      ephemeral-storage: "10Gi"
    limits:
      memory: "16Gi"
      cpu: "4"
      ephemeral-storage: "20Gi"
  
  # Node selection and scheduling
  nodeSelector:
    node-type: "kurrentdb"
    disk-type: "ssd"
  
  # Tolerations for dedicated nodes
  tolerations:
    - key: "kurrentdb"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "high-memory"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 3600
  
  # Anti-affinity to spread pods across nodes
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: "kurrentdb"
              app.kubernetes.io/instance: "kurrentcluster-advanced"
          topologyKey: "kubernetes.io/hostname"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: "kurrentdb"
                app.kubernetes.io/instance: "kurrentcluster-advanced"
            topologyKey: "topology.kubernetes.io/zone"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "node-type"
                operator: "In"
                values: ["kurrentdb", "database"]
              - key: "kubernetes.io/arch"
                operator: "In"
                values: ["amd64"]
  
  # Custom service account
  serviceAccountName: "kurrentdb-service-account"
  
  # Additional environment variables for advanced configuration
  environment:
    - name: KURRENTDB_LOG_LEVEL
      value: "Debug"
    - name: KURRENTDB_WORKER_THREADS
      value: "8"
    - name: KURRENTDB_PREPARED_COUNT
      value: "2000"
    - name: KURRENTDB_COMMIT_COUNT
      value: "2000"
    - name: KURRENTDB_WRITE_THROUGH
      value: "true"
    - name: KURRENTDB_CHUNK_CACHE_SIZE
      value: "536871424"  # 512MB
    - name: KURRENTDB_DB_CACHE_SIZE
      value: "1073741824" # 1GB
    - name: KURRENTDB_STATS_PERIOD_SEC
      value: "30"
    - name: KURRENTDB_DISABLE_HTTP_CACHING
      value: "false"
    - name: KURRENTDB_STREAM_INFO_CACHE_CAPACITY
      value: "100000"
